### ISSUE TITLE
Cannot Instantiate using the Example

### ISSUE THREAD

**Issue by dhbrand** [agaveplatform/r-sdk#2]
Running through the example using the Docker environment and receiving an error when running the 
` ag <-Agave$new` command.  
The console output is below.  In the instructions you might mention to the user to change their working directory to the examples folder and the install("..") to install("../rAgave")

`R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Error in loadNamespace(name) : there is no package called ‘rmarkdown’
31 Jan 2018 17:34:20 [rsession-rstudio] ERROR r error 4 (R code execution error) [errormsg=Error in loadNamespace(name) : there is no package called ‘rmarkdown’
]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) /home/ubuntu/rstudio/src/cpp/r/RExec.cpp:159; LOGGED FROM: void rstudio::session::modules::rmarkdown::notebook::{anonymous}::onDocAdded(const string&) /home/ubuntu/rstudio/src/cpp/session/modules/rmarkdown/NotebookCache.cpp:341
> library("rAgave")
> # For security, we'll pull our variables from the environment rather than enter them directly. 
> myCreds <- Sys.getenv( c("AGAVE_USERNAME", "AGAVE_PASSWORD", "AGAVE_TENANT", "AGAVE_BASE_URL"), names = TRUE )
> # Prompt for them if not present, and store them in the environment in case we rerun this later.
> if (is.null(myCreds[["AGAVE_USERNAME"]]) || nchar(myCreds[["AGAVE_USERNAME"]]) == 0) {
+   myCreds[["AGAVE_USERNAME"]] <- readline("Agave username:")
+   Sys.setenv(AGAVE_USERNAME = myCreds[["AGAVE_USERNAME"]])
+ }
Agave username:dhbrand
> 
> if (is.null(myCreds[["AGAVE_PASSWORD"]]) || nchar(myCreds[["AGAVE_PASSWORD"]]) == 0) {
+   myCreds[["AGAVE_PASSWORD"]] <- readline("Agave password:")
+   Sys.setenv(AGAVE_PASSWORD = myCreds[["AGAVE_PASSWORD"]])
+ }
Agave password:Engaged1001
> 
> if (is.null(myCreds[["AGAVE_BASE_URL"]]) || nchar(myCreds[["AGAVE_BASE_URL"]]) == 0) {
+   myCreds[["AGAVE_BASE_URL"]] <- readline("Agave base url (https://public.agaveapi.co):")
+   Sys.setenv(AGAVE_BASE_URL = myCreds[["AGAVE_BASE_URL"]])
+ }
Agave base url (https://public.agaveapi.co):
> #detach("package:futile.logger", unload=TRUE)
> #detach("package:rAgave", unload=TRUE)
> install("..")
Error: Could not find package root.
> getwd()
[1] "/home/rstudio"
> setwd("~/examples")
> library("rAgave")
> # For security, we'll pull our variables from the environment rather than enter them directly. 
> myCreds <- Sys.getenv( c("AGAVE_USERNAME", "AGAVE_PASSWORD", "AGAVE_TENANT", "AGAVE_BASE_URL"), names = TRUE )
> #detach("package:futile.logger", unload=TRUE)
> #detach("package:rAgave", unload=TRUE)
> install("..")
Error: Could not find package root.
> getwd()
[1] "/home/rstudio/examples"
> #detach("package:futile.logger", unload=TRUE)
> #detach("package:rAgave", unload=TRUE)
> install("../rAgave")
Installing rAgave
'/usr/local/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  '/home/rstudio/rAgave' --library='/usr/local/lib/R/site-library' --install-tests 

* installing *source* package ‘rAgave’ ...
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘rAgave’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (rAgave)
Reloading installed rAgave
> ag <-Agave$new( baseUrl = myCreds[["AGAVE_BASE_URL"]],
+                 username = myCreds[["AGAVE_USERNAME"]], 
+                 password = myCreds[["AGAVE_PASSWORD"]])
cannot open file 'agave.log': Permission deniedError in file(file, ifelse(append, "a", "w")) : 
  cannot open the connection`

**Comment by deardooley** [comment]
Thanks for giving it a shot. Were you running this using the RStudio server from the agaveplatform/rstudio docker image, or a different one?

**Comment by dhbrand** [comment]
I just followed the README.md.  It looks like the Dockerfile calls `rocker/rstudio:3.4.3`.  Should I try the one you just mentioned?

**Comment by deardooley** [comment]
Give the `docker-compose.yml` a shot. You can build the image yourself  `docker-compose build`, or just run it as is using the latest build from our repo. `docker-compose up -d`

**Comment by deardooley** [comment]
You're right. Try to `cd rAgave/examples` when you first start. That should handle any issues with write permissions and let you edit the notebook, create files, folders, etc. an persist it all to your local disk.

**Comment by deardooley** [comment]
There was a bug in the Dockerfile hat granted ownership of that examples directory to user `0755` 
  ¯\_(ツ)_/¯. Doah.
